#!/usr/bin/env bash
# PCPM afterRun hook — auto-generated by global-brain hook-engine
# Extracts knowledge from the completed session transcript and
# writes it back into the persistent brain stores.

BRAIN_CLI="/Users/jeremy/dev/Simone-MCP/src/cli.js"
BRAIN_ROOT="/Users/jeremy/dev/Simone-MCP"
PROJECT_ID="Simone-MCP"
SESSION_ID="session-$(date +%s)"

# Extract knowledge from the session transcript (runs LLM extraction)
node "$BRAIN_CLI" extract-knowledge \
  --root "$BRAIN_ROOT" \
  --project "$PROJECT_ID" \
  --session "$SESSION_ID" \
  2>/dev/null

# Sync project brain bidirectionally
if [ -n "$PROJECT_ROOT" ]; then
  node "$BRAIN_CLI" sync \
    --root "$BRAIN_ROOT" \
    --project "$PROJECT_ID" \
    --project-root "$PROJECT_ROOT" \
    2>/dev/null
fi

echo "PCPM_AFTERRUN_COMPLETE=true"
